import type { Metadata } from "next";
import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import {
    getDestinationsList,
    getGlobalSettings,
    getPackagesList,
} from "@/data/loaders";
import Footer from "@/components/layout/footer";
import { Toaster } from "sonner";

export const runtime = "edge";

const playFairDisplay = Playfair_Display({
    variable: "--font-playfair-display",
    subsets: ["latin"],
});

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

async function loader() {
    const [data, destinations, packages] = await Promise.all([
        getGlobalSettings(),
        getDestinationsList(),
        getPackagesList(),
    ]);
    if (!data && data.data) throw new Error("Failed to fetch global settings");
    return {
        header: data.data?.header,
        footer: data.data?.footer,
        destinations: destinations.data,
        packages: packages.data,
    };
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const { header, footer, destinations, packages } = await loader();
    return (
        <html lang="en">
            <body
                className={`${playFairDisplay.variable} ${manrope.variable} antialiased`}
            >
                <Header
                    {...header}
                    destinations={destinations}
                    packages={packages}
                />
                {children}
                <Footer {...footer} />
                <Toaster richColors position="top-right" />
            </body>
        </html>
    );
}
