import type { Metadata } from "next";
import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import {
    getDestinationsList,
    getGlobalSettings,
    getPackagesList,
} from "@/data/loaders";
import Footer from "@/components/layout/footer";
import { Toaster } from "sonner";
import { dir } from "i18next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";

const playFairDisplay = Playfair_Display({
    variable: "--font-playfair-display",
    subsets: ["latin"],
});

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return routing.locales.map((lng) => ({ locale: lng }));
}

async function loader(locale: string) {
    const [data, destinations, packages] = await Promise.all([
        getGlobalSettings(locale),
        getDestinationsList(),
        getPackagesList(),
    ]);
    if (!data && data.data) throw new Error("Failed to fetch global settings");
    return {
        header: data.data?.header,
        footer: data.data?.footer,
        destinations: destinations.data,
        packages: packages.data,
    };
}

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {
    const locale = (await params).locale;
    const { header, footer, destinations, packages } = await loader(
        locale || "en"
    );

    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    // Enable static rendering
    setRequestLocale(locale);

    return (
        <NextIntlClientProvider>
            <html lang={locale || "en"} dir={dir(locale)}>
                <body
                    className={`${playFairDisplay.variable} ${manrope.variable} antialiased max-w-screen`}
                >
                    <Header
                        {...header}
                        destinations={destinations}
                        packages={packages}
                        locale={locale}
                    />
                    {children}
                    <Footer {...footer} />
                    <Toaster richColors position="top-right" />
                </body>
            </html>
        </NextIntlClientProvider>
    );
}
